### ISSUE TITLE
Run period bound

### ISSUE THREAD

**Issue by azamkamranian** [ugr-sail/paper-drl_building#1]
Hi
I am interested about the run period bounds that were employed in the training of your models. Furthermore, may I request a graphical or numerical representation of the ‘Cooling_Setpoint_RL’ and ‘Heating_Setpoint_RL’ from the monitor file of the evaluation conducted on the 5zone env?

I have encountered numerous challenges when utilizing sinergym. It appears that there are several blind spots associated with the usage of sinergym for Deep Reinforcement Learning

**Comment by manjavacas** [comment]
Dear @azamkamranian, since this repository is mainly used to store the material of the paper, and not to solve technical issues, I encourage you to write an issue in the official [Sinergym](https://github.com/ugr-sail/sinergym) repository so that we can provide you with technical help.

Best regards, and thanks for your interest!
